samples:
  # Adjust/Add other samples if necessary
  35_drug_Rep1: 0_data/reads/3D7_drugtreated_35hpi_Rep1_RNA
  35_drug_Rep2: 0_data/reads/3D7_drugtreated_35hpi_Rep2_RNA
  35_drug_Rep3: 0_data/reads/3D7_drugtreated_35hpi_Rep3_RNA
  35_ctrl_Rep1: 0_data/reads/3D7_nontreated_35hpi_Rep1_RNA
  35_ctrl_Rep2: 0_data/reads/3D7_nontreated_35hpi_Rep2_RNA
  35_ctrl_Rep3: 0_data/reads/3D7_nontreated_35hpi_Rep3_RNA
# Adapters for trimmomatic
adapters: 0_data/TrimmomaticAdapters/Illumina_stranded_mRNA.fa
# Reference files
reference-genome: 0_data/reference/plasmoDB52/PlasmoDB-52_Pfalciparum3D7_Genome.fasta
reference-annotation: 0_data/reference/plasmoDB52/PlasmoDB-52_Pfalciparum3D7.gff
chromSizes: 0_data/reference/plasmoDB52/sizes.genome
# Random seed for reproducibility
rndSeed: 49561
# number of threads used for parallelisation in star/trimmomatic
parallel_threads: 12
