samples:
  # Adjust if necessary
  noKO_24h_Rep1: 0_data/reads/noKO_i24_69hpi_Rep1_MNase
  iKO_24h_Rep1: 0_data/reads/iKO_i24_69hpi_Rep1_MNase
  noKO_24h_Rep2: 0_data/reads/noKO_i24_69hpi_Rep2_MNase
  iKO_24h_Rep2: 0_data/reads/iKO_i24_69hpi_Rep2_MNase
# reference files
reference-genome: 0_data/reference/plasmoDB52/PlasmoDB-52_Pfalciparum3D7_Genome.fasta
reference-annotation: 0_data/reference/plasmoDB52/PlasmoDB-52_Pfalciparum3D7.gff
annotation_NucDyn: 0_data/reference/pf_nucDyn.gff
chromSizes: 0_data/reference/plasmoDB52/sizes.genome
treat-name: "iKO_24h"
control-name: "noKO_24h"
replicates:
  Rep1:
  Rep2:
#  Rep3
danpos-adjust-script: 1_code/AdjustFDR/AdjustFDR.R
danpos-executable: 1_code/DANPOS3/danpos.py
rndSeed: 0
